# Практика #1
Приведите пример кода, в котором продемонстрированы следующие ситуации:

- несколько исключений обрабатываются абсолютно идентичным образом;
- исключения, которые обрабатываются, образуют иерархию `Ex1 <|-- Ex2 <|-- Ex3`, т.е. `Ex3` - подкласс `Ex2`, а `Ex2` - подкласс `Ex1`.
```java
class Ex1 extends Exception {}
class Ex2 extends Ex1 {}
class Ex3 extends Ex2 {}

public class ExceptionHierarchyExample {
    public static void main(String[] args) {
        try {
            // Генерация исключения
            throw new Ex3(); // Можно подставить Ex2 или Ex1 для тестирования
        } catch (Ex3 | Ex2 e) { // Обработка Ex3 и Ex2 идентичным образом
            System.out.println("Handled Ex3 or Ex2: " + e.getClass().getSimpleName());
        } catch (Ex1 e) { // Отдельная обработка Ex1
            System.out.println("Handled Ex1: " + e.getClass().getSimpleName());
        }
        
        // Попытка объединения исключений из одной иерархической цепочки
        // catch (Ex1 | Ex2 e) {} // НЕДОПУСТИМО: Исключения связаны наследованием
    }
}
```

---

# Практика #2
Что означает использование `final` при в данном объявлении?
```java
try {
   ...
} catch (final Exception e) {
   ...
}
```
---
Когда переменная в блоке `catch` объявляется с модификатором `final`, это означает, что она не может быть переназначена.